[2025-09-09T18:49:14.186+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-09T18:49:14.216+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pl_mlops.create_insert_data manual__2025-09-09T18:49:04.576711+00:00 [queued]>
[2025-09-09T18:49:14.223+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pl_mlops.create_insert_data manual__2025-09-09T18:49:04.576711+00:00 [queued]>
[2025-09-09T18:49:14.224+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2025-09-09T18:49:14.239+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): create_insert_data> on 2025-09-09 18:49:04.576711+00:00
[2025-09-09T18:49:14.248+0000] {standard_task_runner.py:72} INFO - Started process 3169 to run task
[2025-09-09T18:49:14.251+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pl_mlops', 'create_insert_data', 'manual__2025-09-09T18:49:04.576711+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/mlops_pl.py', '--cfg-path', '/tmp/tmp814dis4p']
[2025-09-09T18:49:14.254+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask create_insert_data
[2025-09-09T18:49:14.355+0000] {task_command.py:467} INFO - Running <TaskInstance: pl_mlops.create_insert_data manual__2025-09-09T18:49:04.576711+00:00 [running]> on host 217056bd8467
[2025-09-09T18:49:14.513+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khuong' AIRFLOW_CTX_DAG_ID='pl_mlops' AIRFLOW_CTX_TASK_ID='create_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T18:49:04.576711+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-09T18:49:04.576711+00:00'
[2025-09-09T18:49:14.515+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-09T18:50:25.274+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-09-09T18:50:25.276+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-09-09T18:50:25.278+0000] {process_utils.py:132} INFO - Sending 15 to group 3169. PIDs of all processes in the group: [3169]
[2025-09-09T18:50:25.279+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 3169
[2025-09-09T18:51:25.282+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=3169, name='airflow task ru', status='sleeping', started='18:49:13') did not respond to SIGTERM. Trying SIGKILL
[2025-09-09T18:51:25.284+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 3169
[2025-09-09T18:51:25.312+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3169, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='18:49:13') (3169) terminated with exit code -9
[2025-09-09T18:51:25.313+0000] {standard_task_runner.py:190} ERROR - ('Job 9 was killed before it finished (likely due to running out of memory)', 'For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed')
